### ISSUE TITLE
Benützt den Issue Tracker

### ISSUE THREAD

**Issue by nauer** [nauer/WS2016#1]
Posted eure Fragen hier

**Comment by toliosalexander** [comment]
Es ist mir eine Freude, hier den Issue-tracker eröffnen zu dürfen!
Folgendes Problemchen ist bei mir gerade aufgetreten: Ich habe auf meinem lokalen git-Verzeichnis (toliosalexander) zwei Unterordner, einen für die Aufgaben und einen für die Mitschriften. Beide wollte ich nun mit git ins Verzeichnis WS2016 (@nauer) stellen. Dabei ist aber nur der Ordner "Aufgaben" erschienen, der Ordner "Mitschriften" ist ausgegraut; gleichzeitig ist auf meinem git-Profil der Ordner inkl. des Inhaltes erschienen. Hat jemand eine Vermutung, wo hier der Fehler liegt?
Vielen Dank, Alexander Tolios

**Comment by nauer** [comment]
Für jede Frage bitte ein eigenes Issue starten. Ansonsten wird keine eigene Überschrift erstellt und man findet den Issue nicht. Antworten werden dann im Issue selbst abgesetzt.

Habe @toliosalexander Frage in eigenen Issue verschoben und schließe dieses Issue.
Toi toi
