### ISSUE TITLE
Magic Methods

### ISSUE THREAD

**Issue by AnnaMajewski** [nauer/WS2016#10]
Hallo!

Eine Frage zu den Magic Methods. Mir ist klar, dass die von vornherein eine Definition haben, diese dann von uns verändert werden kann, wenn wir das wollen. Damit ändern wir dann das Verhalten der Instanzen einer Klasse. Bei dem Beispiel mit `__repr__`, `__str__` und `__bytes__`, verstehe ich aber nicht wieso immer derselbe Output erfolgt.

``` python
class A:
    def __repr__(self):
        return "A()"
    def __str__(self):
        return "Ich bin vom Typ A"
    def __bytes__(self):
        return b"Ich bin vom Typ A - bytes"

a = A()

str(a)
print(a)

repr(a)
print(a)

bytes(a)
print(a)
```

Ausgabe: 
Ich bin vom Typ A
Ich bin vom Typ A
Ich bin vom Typ A

Ich habe es so verstanden, dass wenn man bytes(a) anwendet, man ein bytes Objekt erzeugt, müsste es dann nicht nach bytes(a) den Block unter **bytes** ausführen?

Liebe Grüße,
Anna

**Comment by AnnaMajewski** [comment]
Oh okay, ich sehe den Fehler selbst ....
Ich habe gar nicht bytes(a) geprintet, sondern nur a...
bei print(bytes(a)) kommt die gewünschte Ausgabe. My bad :)

**Comment by nauer** [comment]
Achtung ich hab noch einen Fehler entdeckt. Vielleicht nur ein copy paste Fehler. Magic Methods fangen an und hören auf immer mit dem doppelten _. In ihrem Fall haben Sie nur einfache Methoden geschrieben.

```python
# not the same
def bytes(self):
    return b"Ich bin vom Typ A - bytes"

def __bytes__(self):
    return b"Ich bin vom Typ A - bytes"
```

**Comment by AnnaMajewski** [comment]
Ah, das ist markdown von dem Forum hier, es hat es als "fett" markiert, statt die __ zu übernehmen.

**Comment by nauer** [comment]
Okay, ich sehe das Problem. Sie müssen wenn Sie Code posten \`var\` = `var` für Oneliner verwenden und wenn sie längere Abschnitte posten verwenden sie diese Form.

\`\`\`python
def func(a):
    print(a)
 \`\`\`

```python
def func(a):
    print(a)
```

Python gibt die Sprache an für das sie das Highlighting haben wollen.

Das \` Zeichen ist das neben den Backspace und nicht das einfache Anführungszeichen.
