### ISSUE TITLE
Aufgabe 17B

### ISSUE THREAD

**Issue by CBTJ** [nauer/WS2016#11]
Die Angabe von Beispiel 17B verlangt die 3 spezial Methoden in den Recordxxx Klassen. Bei der Lösung stehen sie jedoch in der Parser-Klasse, was für mich auch mehr Sinn machen würde. Wie sollen wie die Aufgabe lösen?

**Comment by nauer** [comment]
Sie haben Recht. Das war ein copy/paste Fehler von Aufgabe 16. Die Methoden gehören in die Parser Klasse.
