### ISSUE TITLE
WH Test und Abgabe?

### ISSUE THREAD

**Issue by 23reever** [nauer/WS2016#3]
Bitte um kurze Info, welche Kapiteln/Folien beim nächsten WH Test abgefragt werden und bis wann die Aufgaben und bis wann sollen wir Aufageb 7 und Aufagbe 8 abgeben/hochladen?

**Comment by nauer** [comment]
Zum nächsten WH Test kommt der Teil "Python 3 Einführung_4.pdf"

Versuchen Sie die Aufgaben bis zum nächsten Termin durch zu arbeiten. Dann fallen Ihnen auch die WH Test leichter. Spätestens zum übernächsten Termin  sollten Sie aber oben sein. Ansonsten könnten Sie den Anschluß verlieren.

**Comment by 23reever** [comment]
Vielen Dank für die Antwort.
