### ISSUE TITLE
progressbar.py

### ISSUE THREAD

**Issue by nauer** [nauer/WS2016#6]
Hallo Leute!

Ich habe in meinen Projektordner das Skript progressbar.py erstellt. Sehen Sie sie es durch und versuchen Sie zu verstehen wie der Spinner in der Funktion funktioniert. Wir hatten auch ein Beispiel in der letzten Vorlesung. Sehen Sie Kapitel Namensräume S.12. Wenn Sie es verstanden haben haben Sie bereits einen Punkt im heutigen Test...

Falls noch Unklarheiten sind. Der Issuetracker ist für jeden offen. Ein bisschen Zeit ist noch.

Happy Coding

@nauer

**Comment by 23reever** [comment]
Ich habe Schwierigkeiten den str Ausdruck (<" + str(effective_length) + ") in der print Funktion zu verstehen. 
effective_length (bei length 50) = 44 und mit str als string ausgegeben? Aber 44 wird ja niergends ausgegeben? Ich vermute es wird irgendwie als "Platzhalter" fungieren, aber wie?

**Comment by nauer** [comment]
Mit **'effective_length'** bezeichnet ich die Länge der tatsächlichen Progressbar (####) ohne des Spinners und der Prozentangabe am Ende. Somit ist die gesamte Progressbar nie länger als **'length'**.
\- 6 ergibt sich aus 1 Zeichen für den Spinner 4 Zeichen für den Prozent format String und 1 Zeichen für das Prozentzeichen selbst. Der Rest ist für die Progressbar reserviert.

Interessanter ist aber, warum sich der Spinner dreht, obwohl die Funktion immer wieder neu aufgerufen wird, wie beim ersten mal. Was passiert, wenn ich die Funktion explizit mit **(..., spinner=[])** aufrufe?

Wär mag kann das Programm so umschreiben, dass man progressbar.py eine Liste von Zeichen übergibt die der Spinner dann verwendet.
