### ISSUE TITLE
Fragen zu Aufgabe 11

### ISSUE THREAD

**Issue by nauer** [nauer/WS2016#7]
Hallo Leute!

Ich habe einige Fragen zur Aufgabe 11 gemailt bekommen. Da sie vielleicht auch für andere interessant sind. Poste ich sie einfach hier.

> Wozu bzw. braucht man das `isinstance` in der Zeile 9 im WS2016.py

Der Vorteil von `isinstance` gegenüber von `type` ist, dass sie hier auf mehrere Typen gleichzeitig prüfen können.

```python
value = "test"

isinstance(value, (type1, type2, type3))
```

Zudem funktioniert das auch mit vererbten Klassen.

```python
class A:
    pass

class B(A):
    pass

value = B()

isinstance(value, A)  # True
isinstance(value, B)  # True

```

Was Klassen und Vererbung genau ist, hören Sie in der heutigen Vorlesung.

> Die Berechnung des GC Content setzt aber vor raus, dass der Parser vorher gelaufen ist oder? Weil sonst keine Datenbank generiert ist. Wie überprüfe ich das am besten und wo?

Richtig. Beim Aufruf von `get_gc_content(db, index)` müssen Sie `db` mit dem `index` übergeben. Wenn Sie prüfen möchten, ob es den Index überhaupt gibt, können sie die Länge der `db` Sequenz überprüfen.

```python
if index < len(db):
    pass
```

>In der fasta Parser Datei hast du das Argparse mehrmahlig angewannt in Line 16 erzeugst du den Pointer auf die ARGParse Funktion

Achtung! Es gibt keine Pointer in Python. Sie meinen eine Referenz. In C können Sie zum Beispiel einen Pointer auf Pointer setzen und diese auch dereferenzieren, wenn ich mich recht erinnere. Wenn Sie das mit einer Referenz in Python machen, bekommen Sie nur eine neue Referenz auf das gleiche Objekt.

> mittels der Methode add_argument fügst du in Zeile 21 und 22 etwas hinzu - Kann man dies nicht in einer Zeile tun? Aus dieser Frage leitet sich ab warum ich dies nicht gleich in Zeile 16 der Funktion übergebe - müsste eigentlich ident bleiben, und durch weniger Code schneller oder sehe ich das vollkommen falsch?

In Zeile 16 wird das Objekt nur initiert. Sie können hier zwar bereits Parameter übergeben, aber diese stehen für das Parserobjekt selbst. `add_argument` wird für jede Option, die hinzugefügt werden soll einmal aufgerufen. Ich wüßte nicht wie man das kürzer gestalten könnte.

> Beim Zusammstellen der Funktion macht es einen Unterschied an welcher Stelle der Argument Parser Teil steht? Wegen zeilenweisen Abarbeitung kann ich hier davor Variablen generieren und sonstige Dinge machen, könnte ja eine Zeitverschiebung zum Programmstart entstehen? 

In der Tat. Geparst wird erst beim Aufruf von `parser.parse_args()`. Aber normalerweise wird der argparse Teil zu aller erst ausgeführt um zu prüfen ob die cmdline argumente valide sind.

Ich hoffe ich konnte ihre Fragen zu genüge beantworten.

Happy Coding
@nauer

**Comment by PrometheusABW** [comment]
Am 2016-10-03 um 13:53 schrieb Norbert Auer:
>
> Hallo Leute!
>
> Ich habe einige Fragen zur Aufgabe 11 gemailt bekommen. Da sie vielleicht auch für andere interessant sind. Poste ich sie einfach hier.
>
>     Wozu bzw. braucht man das isinstance in der Zeile 9 im WS2016.py
>
> Der Vorteil von isinstance gegenüber von type ist, dass sie hier auf mehrere Typen gleichzeitig prüfen können.
> value = "test"
>
> isinstance(value, (type1, type2, type3))
>
> Zudem funktioniert das auch mit vererbten Klassen.
> class A:
>     pass
>
> class B(A):
>     pass
>
> value = B()
>
> isinstance(value, A)  # True
> isinstance(value, B)  # True
>
> Was Klassen und Vererbung genau ist, hören Sie in der heutigen Vorlesung.

**Aja ok damit die anpassung im Zeile 11 für binär passt... - wäre es hier aber dann nicht universeller Zeile 11 mit einem " | ">" " zu versehen? Wäre halt ein bisschen langsamer aber ich muss beim import nicht aufpassen ob das binär ist oder nicht sondern gedankenlos wie ein Stream das einfach benutzen :-/**
>
>     Die Berechnung des GC Content setzt aber vor raus, dass der Parser vorher gelaufen ist oder? Weil sonst keine Datenbank generiert ist. Wie überprüfe ich das am besten und wo?
>
> Richtig. Beim Aufruf von get_gc_content(db, index) müssen Sie db mit dem index übergeben. Wenn Sie prüfen möchten, ob es den Index überhaupt gibt, können sie die Länge der db Sequenz überprüfen.
> if index < len(db):
>     pass
>
**Der Sinn hinter der Frage war eigentlich bezogen auf das Objekt ;) ich würde hier eher nur die Sequenz übergeben wollen - wäre redundanter und soweit ich Python bisher verstanden hab wird ja alles von iwo daher importiert und verwendet - deshalb auch die Frage nach den Bibliotheken Suchmaschine ;)**


>     In der fasta Parser Datei hast du das Argparse mehrmahlig angewannt in Line 16 erzeugst du den Pointer auf die ARGParse Funktion
>
> Achtung! Es gibt keine Pointer in Python. Sie meinen eine Referenz. In C können Sie zum Beispiel einen Pointer auf Pointer setzen und diese auch dereferenzieren, wenn ich mich recht erinnere. Wenn Sie das mit einer Referenz in Python machen, bekommen Sie nur eine neue Referenz auf das gleiche Objekt.

**Ja, Sorry schlecht formuliert**
>
>     mittels der Methode add_argument fügst du in Zeile 21 und 22 etwas hinzu - Kann man dies nicht in einer Zeile tun? Aus dieser Frage leitet sich ab warum ich dies nicht gleich in Zeile 16 der Funktion übergebe - müsste eigentlich ident bleiben, und durch weniger Code schneller oder sehe ich das vollkommen falsch?
>
> In Zeile 16 wird das Objekt nur initiert.
**Also ähnlich dem def __init__() ?**
>
> Sie können hier zwar bereits Parameter übergeben, aber diese stehen für das Parserobjekt selbst. add_argument wird für jede Option, die hinzugefügt werden soll einmal aufgerufen. Ich wüßte nicht wie man das kürzer gestalten könnte.
**OK demnach wird dies wohl intern als LISTE oder Dict abgespeichert und eine Übergabe in Form ala parser(hier drin füge ich gleich die Argumente ein) geht nicht
>**
>     Beim Zusammstellen der Funktion macht es einen Unterschied an welcher Stelle der Argument Parser Teil steht? Wegen zeilenweisen Abarbeitung kann ich hier davor Variablen generieren und sonstige Dinge machen, könnte ja eine Zeitverschiebung zum Programmstart entstehen?
>
> In der Tat. Geparst wird erst beim Aufruf von parser.parse_args(). Aber normalerweise wird der argparse Teil zu aller erst ausgeführt um zu prüfen ob die cmdline argumente valide sind.

**Da ich mir eine Standard Abfolge an Code Elementen zugedacht habe erschien es mir zwar logisch wusste aber nicht wo ich es einordnen soll - demnach sollte es aber nach Klassen/Functionsdefinitionen sein aber vor dem Aufruf andere Codeteile**
>
> Ich hoffe ich konnte ihre Fragen zu genüge beantworten.
**Ich hoffe ich hab die Antworten halbwegs richtig verstanden... -_-**

**Comment by nauer** [comment]
> @PrometheusABW: Aja ok damit die anpassung im Zeile 11 für binär passt... - wäre es hier aber dann nicht universeller Zeile 11 mit einem " | ">" " zu versehen? Wäre halt ein bisschen langsamer aber ich muss beim import nicht aufpassen ob das binär ist oder nicht sondern gedankenlos wie ein Stream das einfach benutzen :

Achtung! `|` ist ein Bitoperator. Das hat nichts mit binär mode zu tun. Grundsätzlich kann man Unicode Strings oder Bytes verwenden. Ich haben hier `bytes` verwendet um mit den einfachen `bytearray` arbeiten zu können. Ansonsten musst du mit der `io.StringIO` Klasse arbeiten um das Performenzproblem mit den immutablen Strings zu vermeiden.
