### ISSUE TITLE
Aufgabe 14

### ISSUE THREAD

**Issue by CBTJ** [nauer/WS2016#8]
Mir ist nicht ganz klar, wie das letzte db Dictionary in self._records eingetragen wird, nachdem die For-Schleife zu Ende ist?

**Comment by nauer** [comment]
Sie haben recht der letzte Eintrag fehlt. 

Das Problem bei parsen des Fasta Files liegt darin, dass man erst weiß, ob man die ganze Sequenz eingelesen hat, wenn man bereits einen neuen Header eingelesen hat oder das Fileende erreicht hat.

Letzteres wurde im Code nicht berücksichtigt. Nach dem `EOF` (End of File) erreicht wurde, wurde die Schleife beendet und der letzte Eintrag wurde nicht mehr gespeichert, da das Speichern immer erst dann erledigt wird, wenn ein neuer Header gefunden wird.

Deshalb muss nach Beendigung der `for` Schleife der letzte Eintrag noch gespeichert werden. Entweder einfach danach oder Sie verwenden den `else` Zweig der `for` Schleife

~~~python
for line in stream:
    ...
else:  # End of for loop
    self._records.append(SeqRecordFasta(db['id'], bytes(db['seq']), bytes(db['raw']), db['desc']))
~~~

Ich habe den Code upgedated und sie finden die Zeilen in `nauer/ws2016.py` Zeile 148-149.

**Comment by CBTJ** [comment]
Vielen Dank!

      Von: Norbert Auer <notifications@github.com>
 An: nauer/WS2016 <WS2016@noreply.github.com> 
CC: CBTJ <junoclaudia@yahoo.de>; Author <author@noreply.github.com>
 Gesendet: 11:24 Donnerstag, 20.Oktober 2016
 Betreff: Re: [nauer/WS2016] Aufgabe 14 (#8)
   
Sie haben recht der letzte Eintrag fehlt. Das Problem bei parsen des Fasta Files liegt darin, dass man erst weiß, ob man die ganze Sequenz eingelesen hat, wenn man bereits einen neuen Header eingelesen hat oder das Fileende erreicht hat.Letzteres wurde im Code nicht berücksichtigt. Nach dem EOF (End of File) erreicht wurde, wurde die Schleife beendet und der letzte Eintrag wurde nicht mehr gespeichert, da das Speichern immer erst dann erledigt wird, wenn ein neuer Header gefunden wird.Deshalb muss nach Beendigung der for Schleife der letzte Eintrag noch gespeichert werden. Entweder einfach danach oder Sie verwenden den else Zweig der for Schleifefor line in stream:
    ...
else:  # End of for loop
    self._records.append(SeqRecordFasta(db['id'], bytes(db['seq']), bytes(db['raw']), db['desc']))Ich habe den Code upgedated und sie finden die Zeilen in nauer/ws2016.py Zeile 148-149.—
